import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import StoreProvider from "../../lib/StoreProvider";
import { Toaster } from "react-hot-toast";
import { AuthGuard } from "@/lib/hooks/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Discus Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AuthGuard>{children}</AuthGuard>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
